### ISSUE TITLE
IOS 10 backup 

### ISSUE THREAD

**Issue by RomanEmelyanov** [dunhamsteve/ios#1]
Hi!

IOS 10 give me error:

$ ./irestore 'iPhone 10' ls
Selected iPhone 10 a1e3293725e3b6ef52ced35fcaaf5c5322a6df39
2016/11/04 08:58:31 illegal base64 data at input byte 8
$

Any suggestion?

**Comment by dunhamsteve** [comment]
This is now happening for me too, it was working previously, so I'm guessing they changed the format.   I'll take a look at it this weekend.

**Comment by dunhamsteve** [comment]
Yeah, the format changed, they no longer do the sketchy encryption. (Which took me a little while to figure out in the first place.)  I'm checking in a fix for this, but the code will no longer work with older versions of iOS 10.  I'm also fixing the iOS 9 issue.
