### ISSUE TITLE
IOS 9 backup issue

### ISSUE THREAD

**Issue by RomanEmelyanov** [dunhamsteve/ios#2]
Hi!

iphone-dataprotection unpack this backup fine

$ ./irestore 'iPhone 9' restore HomeDomain hd9
Selected iPhone 9 628386133e1b0c488234d2a0770b9b60b733e764
Backup Password: panic: Bad Password

goroutine 1 [running]:
panic(0x4253e00, 0xc4202b54a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/dunhamsteve/ios/backup.(*MobileBackup).SetPassword(0xc4201a8000, 0xc4202b5490, 0x4, 0x11, 0x0)
	/usr/local/go/src/github.com/dunhamsteve/ios/backup/backup.go:133 +0x42e
main.restore(0xc4201a8000, 0x7fff5fbffcca, 0xa, 0x7fff5fbffcd5, 0x3)
	/Users/ers/GO/ios/cmd/irestore/irestore.go:206 +0x9cf
main.main()
	/Users/ers/GO/ios/cmd/irestore/irestore.go:313 +0x881

**Comment by dunhamsteve** [comment]
I can reproduce this also.  It's possible I broke this when I added the iOS 10 support. I'll take a look.

**Comment by dunhamsteve** [comment]
The code to double check the password for iOS 10 was accidentally applied to older iOS 9 format backups.  This is fixed in b2739c7.
