### ISSUE TITLE
about aes gcm

### ISSUE THREAD

**Issue by xdeng** [dunhamsteve/ios#7]
I can't decrypt it with the EVS_aes_256_gcm method of openssl.
Can you tell me what is the difference between gcm and standard?

**Comment by dunhamsteve** [comment]
The change I made was a tweak to allow an empty nonce (initialization vector). The change was made against the go 1.3 implementation of GCM.  I see that go now allows you to specify the nonce size, I'll have to check if I can switch back to their version.

Per my notes in the source, the initial counter ends up as all zeros in this case. (If you pass in all zeros as an iv, it looks like it gets a 1 set the last byte.)  I'd have to dig a little more to figure out how to do this with openssl. But it looks like they explicitly disallow an empty IV:

        case EVP_CTRL_AEAD_SET_IVLEN:
            if (arg <= 0)
                return 0;

If you're using openssl, you might have to patch that check or tweak the gctx out from under it. (I don't have time to further dig in the openssl source at the moment.

**Comment by dunhamsteve** [comment]
This is the relevant part of my initial patch to the go implementation of GCM:

```
@@ -126,9 +101,6 @@
 var errOpen = errors.New("cipher: message authentication failed")
 
 func (g *gcm) Open(dst, nonce, ciphertext, data []byte) ([]byte, error) {
-	if len(nonce) != gcmNonceSize {
-		panic("cipher: incorrect nonce length given to GCM")
-	}
 
 	if len(ciphertext) < gcmTagSize {
 		return nil, errOpen
@@ -138,12 +110,18 @@
 
 	// See GCM spec, section 7.1.
 	var counter, tagMask [gcmBlockSize]byte
-	copy(counter[:], nonce)
-	counter[gcmBlockSize-1] = 1
+
+	if len(nonce) != gcmNonceSize {
+		// counter is all zeros for apple's blank iv
+		// The python code seems to do the hash inside g.auth for non-12 byte IVs
+
+	} else {
+		copy(counter[:], nonce)
+		counter[gcmBlockSize-1] = 1
+	}
 
 	g.cipher.Encrypt(tagMask[:], counter[:])
 	gcmInc32(&counter)
```

**Comment by xdeng** [comment]
Thank you for your answer, I tried to modify the openssl

**Comment by dunhamsteve** [comment]
I've confirmed that the stock Go GCM works now, and I've switched back to it.  I tried the following with openssl, but it didn't work. It might be necessary to try a different GCM implementation.  Otherwise you'll want to compare the internal state of both implementations at the beginning of the first block and try to figure out why they are different.

```c
  AES_KEY key;
  if (AES_set_decrypt_key(keyData, 256, &key))
    fail("set key");

  GCM128_CONTEXT *ctx = CRYPTO_gcm128_new(&key, AES_decrypt);
  CRYPTO_gcm128_setiv(ctx, NULL, 0);

  if (CRYPTO_gcm128_decrypt(ctx,data,out,dlen-16))
    fail("decrypt");
```

**Comment by xdeng** [comment]
Thank ~ I found a project that supports iv as null on github.

**Comment by xdeng** [comment]
https://gist.github.com/networkextension/013e510e1d711ff9cd6c9f8d13f850c5     call even with NULL pointer and zero length IV

https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60027/Source/API/CommonGCMCryptor.c
